name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      # 设置 Node.js 20 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 安装依赖项
      - name: Install dependencies
        run: npm install

      # 执行构建 (tsc && vite build)
      - name: Build project
        run: npm run build

      # 上传到 FTP 根目录
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./dist/
